#!/usr/bin/env zsh

printUsage() {
  echo "Usage: ${1} <levelNb>"
  exit 1
}

[ -z "${1}" ] && printUsage "${0}"

levelNb=$(printf "%02d" "${1}")
subdir="level${levelNb}"

mkdir -p "${subdir}/Ressources/assets"
echo "# ${subdir}" >> "${subdir}/Ressources/README.md"
touch "${subdir}/flag"
